### ISSUE TITLE
[Suggestion] rescan contracts when there is a new version of mythril installed

### ISSUE THREAD

**Issue by tzapu** [cleanunicorn/karl#6]
assuming that a new version of mythril would be able to detect possible new problems, it would make sense to keep a list of scanned/to scan contracts, and re-scan them on each new version of mythril

**Comment by cleanunicorn** [comment]
I'm thinking of giving the opportunity of starting from a specific block, specifying something like `--block [number]` it would make karl start the scan from there.
Would this work for you @tzapu ?
