### ISSUE TITLE
[Suggestion] Have a minimal http or ws API to check specific contracts

### ISSUE THREAD

**Issue by tzapu** [cleanunicorn/karl#8]
it would be very nice if you could request it to scan a specific contract. you give it an address, it eth_getCode s the binary, scans it and presents the results... that might come in very handy

**Comment by cleanunicorn** [comment]
I don't think I will implement this because it completely shadows the Mythril implementation.

You can obtain the same thing by running Mythril
```console
$ myth -x -a [0xcontractaddress]
```

Soon enough we will also provide an API that you can send source code to and receive the results.
