### ISSUE TITLE
Limit Requests to Avoid 429 Exception

### ISSUE THREAD

**Issue by Danc2050** [cleanunicorn/karl#81]
At times, the requests that karl makes to infura cause the following error:

```
ERROR:Karl:Exception: 429 Client Error: Too Many Requests for url: https://mainnet.infura.io/
<traceback object at 0x7f0edc560688> 
```

If karl determined the minimum time it could send requests to infura without triggering the 429 error, it could work within that bound and still make progress while not halting the execution of the program entirely due to a 429 error.

**Comment by cleanunicorn** [comment]
My recommended way is to create a free account to Infura and use the generated URL. 

This way it will not generated the 429 error.

Do you still think a rate limit makes sense? I want to scan as fast as possible and it's really easy to fix the issue.

**Comment by Danc2050** [comment]
Hi Luca.

First off, thanks for responding. I think your tool is really a great idea. I want to do something similar, except just parse the output of mythril output on new contracts as they are put on the blockchain, so this is a real gem of a program.

I do not know much about infura requests. However, I do remember getting a similar error with a free account and tinkering with my own program(s) too quickly. I don't know how getting a free account would be different here. Additionally, if the requests made are greater than 100,000, then a free account would not be able to sustain karl being turned on 24/7.

No need to change anything on my account. I could probably read into the code more and change it if I really had a problem.

**Comment by cleanunicorn** [comment]
Getting a free account will unlock some limits when you use the URLs that look like `https://mainnet.infura.io/v3/yourpersonalkeyhere`, but indeed they are limited to 100k/day.

Implementing threads is probably a good idea. At the moment everything is single thread.

**Comment by Danc2050** [comment]
Nice. I'll check it out. As a short-term fix, I found that changing the value in this line to 5 also prevents the 429 error from happening thus far (Note: lower numbers could work as well, I haven't tried).
https://github.com/cleanunicorn/karl/blob/88a19bee02e9042025c23f5c313ed12261cc1bbb/karl/karl.py#L132

I'll try and come up with a multi-threaded version and do a pull request to see if you like it. It would probably only be ~10 lines added at most.

**Comment by cleanunicorn** [comment]
I'll close this until there's more activity.
